version: '3.7'

volumes:
  go-tools:
    driver: local

services:
  conduit:
    build:
      context: .
    environment:
      - ENV=dev
      - CONDUIT_S3_EGRESS_BUCKET=egress
      - CONDUIT_QUEUE_URL=http://localstack:4566/000000000000/ingress-queue
    volumes:
      - go-tools:/go/bin
      - ~/.aws/:/root/.aws/:ro
      - ~/.ssh/:/root/.ssh/:ro

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DATA_DIR=/tmp/localstack
      - DEBUG=1
      - SERVICES=s3,sqs,sns
    volumes:
      - "./scripts/aws-init.sh:/docker-entrypoint-initaws.d/aws-init.sh"
